### ISSUE TITLE
Add link to source/project for open source snaps

### ISSUE THREAD

**Issue by wesinator** [canonical/snapcraft.io#1322]
### Expected behaviour
Link to source and license page from the details for snaps with an open source license.

### Steps to reproduce the problem
https://snapcraft.io/gedit

No link to the source/project from the snap page.

### Specs

- _URL:_ https://snapcraft.io/gedit
- _Operating system:_ Ubuntu 18.04
- _Browser:_ Firefox

**Comment by popey** [comment]
The source for gedit is on gitlab at https://gitlab.gnome.org/GNOME/gedit and the yaml which produces the snap is in that repo at https://gitlab.gnome.org/GNOME/gedit/blob/master/snap/snapcraft.yaml

**Comment by Lukewh** [comment]
@wesinator & @mig4 I've created a [topic on the forum](https://forum.snapcraft.io/t/ability-to-include-a-link-to-the-source-in-stores/9349) to open the discussion up to the wider team. Thanks for the suggestion :+1:

**Comment by anthonydillon** [comment]
This needs a priority

**Comment by soumyaDghosh** [comment]
I think this issue is resolved, so, can be closed.
