### ISSUE TITLE
Snap title in the store listing does not inherit the `title` field from the snap

### ISSUE THREAD

**Issue by brlin-tw** [canonical/snapcraft.io#1709]
### Expected behaviour
When the snap sets the `title` field and the metadata has not overridden the value of the `title` field is applied to the snap's "Title" field in the store listing

### Steps to reproduce the problem
1. Set up a snap repository with the `title` field set
1. Set up BSI with the repository
1. Browse the snap listing page after the snap is published

### Specs

- _URL:_ https://snapcraft.io/_snap_identifier_/listing
- _Operating system:_ Ubuntu 18.04 AMD64
- _Browser:_ Mozilla Firefox 65.0.1

**Comment by galgalesh** [comment]
Any progress on this @Lukewh ?

**Comment by jgneff** [comment]
I just promoted the [OpenJFX Snap](https://snapcraft.io/openjfx) to the *stable* channel with the "Update metadata on release" setting enabled for the first time.

It looks as if the **Title:** in the store listing is being picked up from the `name:` top-level metadata in the `snapcraft.yaml` file. In this case, that was the "openjfx" lower-cased name. It should be getting the **Title:** in the store listing from the `title:` metadata in the `snapcraft.yaml` file, which is the properly-cased "OpenJFX" name.

I'll update the store listing manually until this is fixed.

**Comment by galgalesh** [comment]
Any progress on this? This issue is still present today.

**Comment by Lukewh** [comment]
We'll discuss this with the store team in our weekly meeting this afternoon. It appears to be an issue with inconsistent extraction from `name` and/or `title` fields. I'll add a comment to this issue later after the meeting.

**Comment by Lukewh** [comment]
The issue has been raised with the store team, who will be prioritising the issue in their next sprint (starting next week).

**Comment by verterok** [comment]
Hi,

I can confirm the title is being changed to the name when releasing a new revision to stable with `Update metadata on release` enabled
We are working on a fix.

Cheers

**Comment by verterok** [comment]
The fix is live on production, please let us know if it doesn't work as expected.

Cheers

**Comment by Lukewh** [comment]
Thanks @verterok closing this issue.

Please reopen if needed anyone!
