### ISSUE TITLE
Refactor try/except in all the routes

### ISSUE THREAD

**Issue by jkfran** [canonical/snapcraft.io#3230]
Currently we have this code duplicated multiple times in the application for all the routes using the API

https://github.com/canonical-web-and-design/snapcraft.io/blob/1cf85f9f3da332d5ec55bcbce48626554ac22925/webapp/publisher/snaps/listing_views.py#L49-L57

I think we can improve it by using flask `errorhandler` decorators like we are doing on Charmhub:
https://github.com/canonical-web-and-design/charmhub.io/blob/master/webapp/handlers.py

**Comment by Lukewh** [comment]
While we're doing this, it would be good to send some errors sentry as warnings, instead of errors.
