### ISSUE TITLE
Snap installs section is empty when metrics aren't available 

### ISSUE THREAD

**Issue by anasereijo** [canonical/snapcraft.io#3669]
### Steps to reproduce the problem
- log in on snapcraft.io
- go to [My published snaps](https://snapcraft.io/snaps) page

### Expected behaviour
- have a message telling the user that no metrics are available yet or hide that section until metrics are available 

### How it looks like

<img width="1346" alt="Screenshot 2021-09-06 at 11 55 48" src="https://user-images.githubusercontent.com/36884067/132206906-28eb05ae-fc2b-4304-8506-e67bf2b018a8.png">

### Specs

- _URL:_ [https://snapcraft.io/snaps](https://snapcraft.io/snaps)
- _Operating system:_ macOS Big Sur
- _Browser:_ Chrome Version 92.0.4515.159

**Comment by jkfran** [comment]
We should have an empty state when there are no metrics
