### ISSUE TITLE
Release UI: Action bar at the bottom of the screen isn't obvious

### ISSUE THREAD

**Issue by Lukewh** [canonical/snapcraft.io#4019]
I always have to double take when I make a change - the bar at the bottom, below the footer, is unintuitive.
![image](https://user-images.githubusercontent.com/479384/172391074-1ab2e47c-6f3b-46d4-ae5d-76ae79a3cc7e.png)

For a shorter page, could it be fixed to the top of the footer?
![image](https://user-images.githubusercontent.com/479384/172391304-79e424ae-03ed-4766-a20a-918b4dfc9de6.png)

We need to discuss

**Comment by AnnSoMuller** [comment]
Let's check that with @anasereijo and @Zoospora :)
That might be worth having the consistency with the toolbar, on top

**Comment by Zoospora** [comment]
I hope to do this on Tuesday with @anasereijo  (Monday is holiday bank for her and I understand she must give me her perspective first 😊

**Comment by Zoospora** [comment]
Waiting for Ana's return and for her to have time to comment on it.

**Comment by anasereijo** [comment]
@Lukewh that shouldn't be happening, should appear above the footer. However, as it was pointed out in the meeting, we do have some sort of action bar at the top of the tab content (see screenshot) and it should be consistent across pages/tabs. ![Screenshot 2022-09-22 at 14.11.46.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/eba68839-80a3-433b-bee4-94a1bca2e85c).

Therefore, I suggest we mock up the Releases tab having it at the top and sticky as we have on Listings tab, with similar design to the current one (at the bottom and keeping the chevron to expand). We can also try the opposite, having it always at the bottom.
@Zoospora is this something you can explore, and we can see both options and make a final decision?

**Comment by Zoospora** [comment]
Sure, I'll do it!

**Comment by Zoospora** [comment]
As a quick draft (not pixel perfect) I have created these two different options, let me know what you think and what iterations you would like to do on it.

![Action bar - TOP.png](https://images.zenhubusercontent.com/62e79f8c438b6a830a3efb99/e5dfbfb9-7600-4344-aa55-739341721d0e)

![Action bar - BOTTOM.png](https://images.zenhubusercontent.com/62e79f8c438b6a830a3efb99/77282877-2f4b-434f-9dab-d78c807f7ef6)

Here [the link to the file](https://www.figma.com/file/A82rp4qLI6C53ZjYUopTY4/22.10-Snapcraft---Snap-action-bar?node-id=1%3A4199)

**Comment by Lukewh** [comment]
@Zoospora on the releases page when you make changes the bar summarizes them:
**Closed**
![image](https://user-images.githubusercontent.com/479384/191944852-63dc96a5-f042-4b57-b129-eea06afe340e.png)

**Open**
![image](https://user-images.githubusercontent.com/479384/191944888-777b65f4-92ff-4ea0-bb05-e8626eb4acf2.png)

**Comment by anasereijo** [comment]
@Zoospora let's chat about this over a call, might be easier

**Comment by Zoospora** [comment]
Perfect, thanks to both of you. I'll start working with that and monday Ana and me will talk about the spacific issues.

**Comment by anasereijo** [comment]
@Zoospora I had a look with @AnnSoMuller and UX wise we think it's good 👍 

Perhaps it's a good idea to also check the Brand store design — it's a side panel, so it's a different use case, but might need some visual updates for consistency? Or maybe not :)

Adding a label for Visual review needed

**Comment by Zoospora** [comment]
Sure, I thought I added so thanks!

**Comment by Zoospora** [comment]
Spencer has reviewed the design and is fine with it as is. He has suggested adding an "info" icon accompanying the "1 update" text as long as it makes sense from a UX perspective. 
https://www.figma.com/file/A82rp4qLI6C53ZjYUopTY4/22.10-Snapcraft---Snap-action-bar?node-id=1%3A4199
In the link you can see three rows:

1- Visual references (not important)
2- Design without info icon
3- Design with info icon

@anasereijo , take a look if you can and let me know. 

Once you give the ok I will polish it quickly (margins and spacing) as this started as a draft. 
Thanks again!!

**Comment by anasereijo** [comment]
@Zoospora I don't see an issue on using the info icon, if you both think it will help the experience/visual. Thanks for this! 👍

**Comment by Zoospora** [comment]
Thanks Ana, I will make the final adjustments and close the issue.

**Comment by Zoospora** [comment]
Ready:
https://www.figma.com/file/A82rp4qLI6C53ZjYUopTY4/22.10-Snapcraft---Snap-action-bar?node-id=56%3A6622

**Comment by Lukewh** [comment]
Implementation: https://github.com/snapcraft.io/issues/4128
