### ISSUE TITLE
unable to find new and updated snaps on snapcraft.io easily

### ISSUE THREAD

**Issue by alculete** [canonical/snapcraft.io#4024]
### Expected behavior
List all new and updated snaps 
### Steps to reproduce the problem
open snapcraft.io > Search for new snaps or search for updated snaps.
The only snaps lists are category or featured snaps there are featured snaps that are 2 years old

**Comment by fitojb** [comment]
Yup! I miss a “Recently updated” feed or page too!

**Comment by keshavbhatt** [comment]
Any update on this? 

It will be really nice to have a section that shows the recently updated snaps in the store.

**Benifits:**
- This will have positive engagement for apps that the developers are updating timely
- This will encourage developers to update their snaps as it will expose thier snaps to audience

**Inspiration:**
We already have something similar in Flathub 
- a dedecated page showing recently updated apps -> https://flathub.org/apps/collection/recently-updated 
- there is also a section on home page of website that shows the recetly updated apps

**Comment by Lukewh** [comment]
Duplicate of https://github.com/canonical/snapcraft.io/issues/2921
