### ISSUE TITLE
Tutorials page returns Internal Server Error

### ISSUE THREAD

**Issue by waveform80** [canonical/snapcraft.io#4068]
The status page suggests nothing is currently down, but the problem has persisted for about 6 hours or so.

### Expected behaviour

Visiting the [Tutorials](https://snapcraft.io/docs/snap-tutorials) section of the Snapcraft Docs pages shows me some tutorials.

### Steps to reproduce the problem

Visit the [Tutorials](https://snapcraft.io/docs/snap-tutorials) page (either directly from that link, or by visiting [Snapcraft](https://snapcraft.io/), selecting [Docs](https://snapcraft.io/docs) and selecting the "Tutorials" link.

### Specs

- _URL:_ https://snapcraft.io/docs/snap-tutorials
- _Operating system:_ Ubuntu
- _Browser:_ Firefox

**Comment by Lukewh** [comment]
I have done a quick fix for the issue and a PR to resolve the underlying issue https://github.com/canonical/canonicalwebteam.discourse/pull/140.
