### ISSUE TITLE
First character of message is always duplicated

### ISSUE THREAD

**Issue by maxcel2** [canonical/snapcraft.io#4069]
### Expected behaviour
Only one instance of each character typed, should appear

### Steps to reproduce the problem
Start typing a message, the first character will always be duplicated. 

### Specs

- _URL:_
- _Operating system:_
- Release Linux Mint 20.3 Una 64-bit
- Kernel Linux 5.4.0-122-generic x86_64
- MATE 1.26.0
- _Browser:_
- Firefox for Linux Mint 102.0.1 (64_bit)

**Comment by Lukewh** [comment]
Which page are you seeing this on @maxcel2?

**Comment by maxcel2** [comment]
> Which page are you seeing this on @maxcel2?

On any chat page where it says 'Type a message', when I start typing, the first character is always duplicated. The same fault occurs on both of my computers, so is not isolated to one machine. This is a relatively recent bug, I cannot recall it happening when I first installed WhatsApp desktop, so perhaps it is related to a recent update.

**Comment by Lukewh** [comment]
This sounds like an issue with a specific snap? This issue tracker is for the website snapcraft.io. Which whatsapp snap are you using? I should be able to point you in the right direction to report it upstream.

**Comment by maxcel2** [comment]
Looking at the Package Manager, I don't appear to have snap, snapd of snapcraft installed.

**Comment by Lukewh** [comment]
What app is your issue with @maxcel2?

**Comment by maxcel2** [comment]
> What app is your issue with @maxcel2?

If you mean, what is my version of WhatsApp-Desktop, it is 0.6.1

**Comment by Lukewh** [comment]
Ah, this issue tracker is for the website https://snapcraft.io not for specific snap issues, unfortunately we have no control over resolving issues within a snap, so I'll close this issue.

Apologies, I don't seem to be able to find WhatsApp-Desktop on https://snapcraft.io/search, so I can't find a link to where you should raise your issue.
