### ISSUE TITLE
Internal Server error when trying to save changes in listing page

### ISSUE THREAD

**Issue by N1sek** [canonical/snapcraft.io#4104]
### Expected behaviour
Listing should be updated

### Steps to reproduce the problem
Go to the listing app page, add some changes and press save button

### Specs

- _URL: listing page
- _Operating system: Ubuntu/iOS
- _Browser: Firefox/Safari/Chrome

![Captura desde 2022-09-19 18-00-03](https://user-images.githubusercontent.com/66885386/191061454-cbef525f-597a-427f-ae25-bc4141b5fc76.png)

**Comment by steverydz** [comment]
Thanks for reporting this issue. It looks as though this is resolved now, but feel free to reopen the issue if you have any more problems.

**Comment by N1sek** [comment]
Now everything works fine except when I want to add an image or when I want to update contact information.
When I want to update one of those two it gives me the same error.

**Comment by steverydz** [comment]
@N1sek I've reopened the issue and look into it

**Comment by steverydz** [comment]
@N1sek Hi, are you still experience this issue? We're not able to recreate it.

**Comment by steverydz** [comment]
I'm closing this as it looks like the error is no longer occurring.
