### ISSUE TITLE
Changing screenshots and category disables Update Metadata on Release

### ISSUE THREAD

**Issue by galgalesh** [canonical/snapcraft.io#4108]
### Expected behaviour

Changing screenshots and category in a snap listing should have no effect on "update metadata on release". These things can only be set using snapcraft.io GUI so they cannot be overwritten by a snap release

### Steps to reproduce the problem

1. Create snap
1. change category
1. save

You will now see a warning that UMoR will be disabled.

**Comment by steverydz** [comment]
Thanks for reporting this issue. We will look into this.

**Comment by steverydz** [comment]
Hi @galgalesh. The fix for this is now live.
