### ISSUE TITLE
Store view doesn't show stores that are fully included in this one

### ISSUE THREAD

**Issue by Roadmaster** [canonical/snapcraft.io#4127]
### Expected behaviour

it'd be nice and save us support workload and customer confusion if, when a store is fully included in another, this fact was indicated in the store view.

Full-Store inclusion can be checked from the store details API response in store.store-whitelist:

```
$ surl -a production -s production --web-login https://dashboard.snapcraft.io/api/v2/stores/a-store-identifier | jq '.store."store-whitelist"'
[
  "ubuntu"
]
```

The above indicates that the `a-store-identifier` store fully includes the `ubuntu` store (the global store).

### Steps to reproduce the problem

https://snapcraft.io/admin/a-store-identifier/snaps

and there's no indication anywhere that the Global (ubuntu) store is included. Therefore then they try to cherry-pick snaps from it, nothing shows because all snaps in global store are already there.

### Specs

- _URL:_ as above
- _Operating system:_ Ubuntu 20.04
- _Browser:_ The One True Browser: Firefox.

**Comment by Lukewh** [comment]
https://warthogs.atlassian.net/browse/WD-1254
