### ISSUE TITLE
Internal Server Error on https://snapcraft.io/qycli-php-testing/builds

### ISSUE THREAD

**Issue by michacassola** [canonical/snapcraft.io#4136]
### Expected behaviour
Page loading

### Steps to reproduce the problem
Loading the page

It happened ever since my last build where I tried out `base: bare`.

- _URL:_ https://snapcraft.io/qycli-php-testing/builds
- _Operating system:_ Windows 11 current (Because of Games and Graphics Design apps)
- _Browser:_ Vivaldi current

**Comment by Lukewh** [comment]
This seems to be fixed? Please reopen if you still have issues.
