### ISSUE TITLE
Store navigation via the sidebar sometimes results in 404

### ISSUE THREAD

**Issue by Roadmaster** [canonical/snapcraft.io#4152]
### Expected behaviour

Stores shown in the sidebar (https://snapcraft.io/admin) should be accessible if I can see them. 

The problem a user reported is that clicking on a particular store in the sidebar results in a 404 error. This happens only when navigating via the sidebar; if they reload, or access the store's URL directly (https://snapcraft.io/admin/whatevs/snaps) it works fine.

### Steps to reproduce the problem

-- From new Chrome Incognito window, go to https://dashboard.snapcraft.io and login. Redirects to https://dashboard.snapcraft.io/store/snaps. See dashboard_after_fresh_login.png
- Click on My Stores redirects to https://snapcraft.io/admin/LimeNET/snaps. See after_click_my_stores.png
- Click on CUSTOMER_STORE in the sidebar. Goes to https://snapcraft.io/admin/STORE_ID/snaps. See customer_sidebar_not_found.png
Now try good URLS after opening a fresh Incognito window:
- Enter https://snapcraft.io/admin/STORE_SLUG/members and login. Shows good_url_base_store.png
- Click on STORE_NAME in the sidebar. Goes to https://snapcraft.io/admin/STORE_ID/snaps. Shows good_url_to_customer_sidebar.png

Note the above was reported by the customer and apparently they can reproduce. I followed the same steps and I could not reproduce. But we both think there might be some state or refresh that's not happening properly in the front-end, this is supported by the fact that a fresh reload works well.

I placed the screenshots in [a private server](https://private-fileshare.canonical.com/~roadmr/issue_4152), since they contain the actual customer name and store IDs.

### Specs

- _URL:_ Per above
- _Operating system:_ (didn't specify)
- _Browser:_ Chrome

**Comment by steverydz** [comment]
Thanks @Roadmaster. I can replicate the issue. It seems to happen if you first navigate to a store that you are a publisher in, then use the navigation to go to another store that you have access to. There seems to be an issue with the state updating correctly. I'll look into this.
