### ISSUE TITLE
Changing Youtube URL and category disables Update Metadata on Release

### ISSUE THREAD

**Issue by merlijn-sebrechts** [canonical/snapcraft.io#4159]
## Expected behaviour

Changing

* Youtube URL
* Category
* Second Category

Should have no effect on "update metadata on release". These things can only be set using snapcraft.io GUI so they cannot be overwritten by a snap release

## Steps to reproduce the problem

1. Create snap in store
1. change category
1.  save

You will now see a warning that UMoR will be disabled.

**Comment by galgalesh** [comment]
Moreover, changing `icon` should disable UMoR, while it does not.

`icon` field is available in the snap and will be overwritten using UMoR, so changing it needs to disable UMoR.

**Comment by Lukewh** [comment]
Tracked internally here: https://warthogs.atlassian.net/browse/WD-488
Status: In progress

**Comment by steverydz** [comment]
This is related to this issue: https://bugs.launchpad.net/snapcraft/+bug/1996904

**Comment by steverydz** [comment]
This is now fixed.

**Comment by merlijn-sebrechts** [comment]
Hey @steverydz 

Thanks for looking into this, but the current behavior still seems off. I tested this with the [axel snap](https://snapcraft.io/axel)

* Changing the first category shouldn't show the warning, but it does.
* Adding a second category shouldn't show the warning, but it does.
* Disabling metrics shouldn't show the warning, but it does.

**Comment by steverydz** [comment]
@merlijn-sebrechts Thanks for the feedback. I've made a fix for the categories so that should go live later today.

In regards to the metrics flags, they do appear to be disabling the update metadata flag so I have left the warning there for now. I've raised an issue with the team responsible for the backend and will update the frontend accordingly once that is resolved.

**Comment by merlijn-sebrechts** [comment]
Great, thanks!
