### ISSUE TITLE
Navigation logo is under the global navigation 

### ISSUE THREAD

**Issue by anthonydillon** [canonical/snapcraft.io#4176]
On small screens the snapcraft logo is under the global navigation.
![Screenshot_2022-12-13-21-54-54-69_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/1413534/207452843-19ff42b6-4cf7-4563-8cbd-8f5b9029524f.jpg)

**Comment by bartaz** [comment]
This was Vanilla bug. Fixed in 3.8.2.
