### ISSUE TITLE
snapcraft.io/docs: Update to add expandable navigation

### ISSUE THREAD

**Issue by degville** [canonical/snapcraft.io#4184]
Can we update https://snapcraft.io/docs to include expandable navigation, as currently used on most of our other documentation sites.

For reference, previous requests for other docs include:
https://github.com/canonical/ubuntu.com/issues/12026 (Ubuntu Core)
https://github.com/canonical/microk8s.io/issues/553 (microK8s).

Thank you!

**Comment by nottrobin** [comment]
@Lukewh could you schedule this in?

**Comment by degville** [comment]
@Lukewh Hello! Any update on this? Time-frame? I'm hoping it's quite straightforward.

**Comment by Lukewh** [comment]
> @Lukewh Hello! Any update on this? Time-frame? I'm hoping it's quite straightforward.

Hi @degville I've created a PR - when the demo is up and running can you take a look and make sure everything is working as expected and comment on the PR, thanks :)
