### ISSUE TITLE
Builds page doesn't work

### ISSUE THREAD

**Issue by mthmulders** [canonical/snapcraft.io#4185]
### Expected behaviour
I am able to see recent builds of my snap.

### Steps to reproduce the problem
When I visit the ['builds' page for my snap](https://snapcraft.io/maven-central-search/builds), I am greeted with an 'Internal Server Error'. This has been going on for months. I have tried using 'incognito' mode in my browser, but the problem persists.

### Specs

- _URL:_ https://snapcraft.io/maven-central-search/builds
- _Operating system:_ macOS 13.1
- _Browser:_ Firefox 108.0.1

**Comment by Lukewh** [comment]
Thanks for the report, we've traced the error and will be fixing in the coming weeks!

**Comment by mthmulders** [comment]
Thanks for the heads up! I'll keep an eye on it. Feel free to reach out if you need any more information or testing from my side.

**Comment by mthmulders** [comment]
Thanks a lot, the "builds" is now working for me!
