### ISSUE TITLE
Add functionality for icon preview

### ISSUE THREAD

**Issue by anasereijo** [canonical/snapcraft.io#4193]
Challenge: avoid 'bad icons' on stores

Solution: Educate the publisher on how to improve their logos and what the best practice is, similar to how other app stores do it.
- add instructions on what is a good icon
- provide a preview of how it will look on light and dark themes. 

<img width="1161" alt="212927163-8aa8b216-c5c5-439e-809f-12dd46073ea2" src="https://user-images.githubusercontent.com/36884067/214897425-dc5e66bc-769b-4d64-98b1-ee02d22c561b.png">

Originally from [here](https://github.com/ubuntu-flutter-community/software/discussions/828?converting=1)

**Comment by anasereijo** [comment]
@LukeNow how much effort is needed to implement this feature?

**Comment by steverydz** [comment]
@anasereijo I assume you meant @Lukewh 😆 

It shouldn't be too much work - we have the preview image so can show it in a different context. How would that preview look? The red squares seem to be the same size as the icon preview?

**Comment by anasereijo** [comment]
@steverydz ooppsss good spot 😅

this is just a rough mock-up, I can do a high fidelity wireframe, or can even brief @Zoospora to design something. 

Thanks for replying! I will try to plan this in then

**Comment by Lukewh** [comment]
I think the dark background could be in the box with a smaller logo? I think it would still be nice to have a light version because I don't think Ubuntu software's light theme isn't actually white? Might be worth getting @Zoospora to have a little tinker. Something to show in work together next week.

**Comment by Zoospora** [comment]
Of course. We can talk about it or even do a quick prototype. I understand what ana says, you can put a couple of pictures with light and dark backgrounds in which you can see how the icon would look like. It could even be a card or just the icon. We can take a look at it.

**Comment by Zoospora** [comment]
Here you can see how on the new design page they use the switch to exemplify light and dark mode. It could be something like this. 
https://design.ubuntu.com/resources

**Comment by anasereijo** [comment]
> Here you can see how on the new design page they use the switch to exemplify light and dark mode. It could be something like this.
> https://design.ubuntu.com/resources

Yes! That would be something nice to explore 👌

**Comment by anasereijo** [comment]
🚀

**Comment by steverydz** [comment]
Proposed design: https://www.figma.com/file/FSSevHu41hyOJJqj7YewiQ/Maintenance?node-id=504%3A1385&t=5HJ0SRCCj4hM7Is2-0
