### ISSUE TITLE
snapcraft.io/README.md: LGPLv3 License Link is pointing to a broken link

### ISSUE THREAD

**Issue by hsmith-dev** [canonical/snapcraft.io#4198]
### Expected behaviour
LGPLv3 License should be displayed upon clicking the hyperlink within the README.md for the LGPLv3 License.

### Steps to reproduce the problem
Navigate to the `LGPLv3` License link within the [README.md](https://github.com/canonical/snapcraft.io/blob/main/README.md)

The link takes you to a [broken link](https://opensource.org/licenses/lgpl-3.0.html) and needs to be updated to the new URL.
![Screenshot from 2023-02-15 11-50-30](https://user-images.githubusercontent.com/42560873/219127013-5663a7a2-878f-4b31-b53b-265577dc4122.png)

**Comment by steverydz** [comment]
@hsmith-dev Thank you for raising this issue. It has now been fixed.

**Comment by hsmith-dev** [comment]
Can you close my PR? I can’t seem to do so. snapcraft.io/README.md: LGPv3 License Link Update by hsmith-dev · Pull Request #4199 · canonical/snapcraft.iogithub.comSent from my iPhoneOn Feb 16, 2023, at 4:41 AM, Steve Rydz ***@***.***> wrote:﻿
@hsmith-dev Thank you for raising this issue. It has now been fixed.
