### ISSUE TITLE
Disable copydoc meta tag on documentation pages

### ISSUE THREAD

**Issue by dboddie** [canonical/snapcraft.io#4201]
The documentation pages contain metadata for Google Drive. See, for example the page source for https://snapcraft.io/docs/snapcraft-setup

Is this something we want to keep, or is it an artifact left over from another process?

**Comment by Lukewh** [comment]
The process is still valid. These copy docs should be updated if and when copy changes. If they are not up-to-date we should make sure they are refreshed.
You can read about the process here: https://discourse.canonical.com/t/how-to-request-an-update-to-our-websites/304

This chrome extension: https://github.com/canonical/ubuntu-copy-docs uses the copydoc meta tag to provide a quick link.

**Comment by evilnick** [comment]
@Lukewh but the copy for this page is actually derived from https://forum.snapcraft.io/t/snapcraft-installation-and-setup/32986
There shouldn't be a copydoc at all for this page because that isn't how it is updated

**Comment by Lukewh** [comment]
I see, so the issue is actually "Disable copydoc meta tag on docs pages"? I'll update the title

**Comment by evilnick** [comment]
thanks
