### ISSUE TITLE
Navigation logo in dedicated installation pages is white-on-white

### ISSUE THREAD

**Issue by fitojb** [canonical/snapcraft.io#4212]
In e.g. https://snapcraft.io/install/pinta/ubuntu

The white logomark is not visible against the white background, and you can only make it out when hovering the logo.

![imatge](https://user-images.githubusercontent.com/554953/222952795-a5d4d227-90d1-45d9-b997-dce3b1572d98.png)

Also, it’s a bit misaligned with the rest of the page.

**Comment by steverydz** [comment]
@fitojb Thanks for raising this issue. It is now fixed and in production.
