### ISSUE TITLE
Snapcrafters have transhuman capabilities - or publisher snap count is wrong

### ISSUE THREAD

**Issue by merlijn-sebrechts** [canonical/snapcraft.io#4226]
The publisher page for Snapcrafters shows 5929 published snaps. Either we're a group of transhumans who have ascended the realm of mere mortals, or something is wrong in this calculation.

https://snapcraft.io/publisher/snapcrafters

## Expected result

This should show something like 90 snaps, if my rough estimate is correct.

**Comment by diddledani** [comment]
I think my stats are often wonky, but my snapstats site is currently reporting a total of 8091 snaps visible publicly. That suggests we're publishing over half of all snaps. I think you're right that something is screwy on snapcraft.io's calculation :-)
