### ISSUE TITLE
Internal server error when listing my snap's "Builds"

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/snapcraft.io#4231]
**Problem:** I've connected my snap source GitHub project to get multi-arch builds. The builds took place because I can see all the new releases, but when I go to the "builds" tab in my snap's dashboard, I get this error:
![image](https://user-images.githubusercontent.com/4047767/227561306-40cc800b-8c32-4646-8fbe-28399be5cfd2.png)

### Expected behaviour
List of snap builds.

### Steps to reproduce the problem
Just attached the following project to my snap: https://github.com/cjdcordeiro/pebble/

### Specs

- _URL:_ https://snapcraft.io/pebble/builds
- _Operating system:_ Ubuntu Jammy
- _Browser:_ Chrome Version 110.0.5481.177 (Official Build) (64-bit)
- _User:_ cristovao.cordeiro@canonical.com

**Comment by Lukewh** [comment]
Thanks for the report! Looks like we're not handling the `bare` base appropriately, I'll push a fix!

**Comment by Lukewh** [comment]
We're having Jenkins issues, but should be today :)
