### ISSUE TITLE
Frequent Shutdowns in Snapcraft Build services

### ISSUE THREAD

**Issue by CapeCrusader321** [canonical/snapcraft.io#4255]
### Expected behaviour
The Build tab is showing internal server error for specific snaps for months , i tried using vpn etc. still same behaviour also tried cleaning cookies and cache, no result.

### Steps to reproduce the problem
This is limited to few snaps only, so cant describe full, just select kvantum or papirus snap tab go to build section and it gives error saying internal server error.

### Specs
4 GB RAM, Intel i3 @ 1.9 Ghz, Using Firefox Snap on Lubuntu 22.04.2

- _URL:_
- _Operating system: https://lubuntu.me/_
- _Browser: https://www.mozilla.org/en-US/firefox/new/_

**Comment by CapeCrusader321** [comment]
Here is how it shows --:

![sc11](https://user-images.githubusercontent.com/100503303/235349542-2364bbf3-9883-49ba-84a4-2189e02a8c13.png)

**Comment by CapeCrusader321** [comment]
This is been persisting for months, and isnt something that happened yesterday...

**Comment by Lukewh** [comment]
Hi @CapeCrusader321 it looks like things have been more stable recently. Some migrations have happened that should improve stability, but please reopen this issue if you see it persisting. Thanks :).
