### ISSUE TITLE
Release Info Disappears

### ISSUE THREAD

**Issue by timhirrel** [canonical/snapcraft.io#4292]
### Specs

- _URL:_ https://snapcraft.io/tdhnet/releases
- _Operating system:_ Ubuntu 20.04, 22.04
- _Browser:_ Firefox, Chrome

**Comment by steverydz** [comment]
@timhirrel Thanks for raising this issue. A fix has now been put into production.

**Comment by timhirrel** [comment]
Thanks for the prompt action!
________________________________
