### ISSUE TITLE
Permanent 'Internal server error' message in Builds tab

### ISSUE THREAD

**Issue by yvs2014** [canonical/snapcraft.io#4360]
Hello, at snap builds tab on snapcraft.io there’s permanent (or at least a couple month ago it was the same) 'Internal Server Error' message:
Internal Server Error Please try again later You can check the service status at status.snapcraft.io. If the problem persists please check the Snapcraft forum or report an issue.

I suppose it’s because snapcraft.yaml is a symlink (in source git repo).
Can you give some hints how to avoid that or how to disable building there?

update:
There's suggestion to disconnect the repo (https://forum.snapcraft.io/t/internal-server-error-at-snap-builds/36166), but I cannot figure out the way how to do that

**Comment by Lukewh** [comment]
Hi @yvs2014 which snap/snaps are you seeing this with?

**Comment by yvs2014** [comment]
@Lukewh that was with mtr085 for a long time, then instead of a symlink to snapcraft.yaml I put a regular file in root directory of git repo as a workaround to get it built on snapcraft

**Comment by Lukewh** [comment]
Ah thanks for the confirmation is was due to the symlink - we can look into that :)

**Comment by Arenukvern** [comment]
Hello, faced the same issue, but in my case it happened only after disconnecting GitHub repository from snapstore.io
my snap is https://snapcraft.io/last-answer

**Comment by Lukewh** [comment]
We're currently having issues with GitHub rate limiting and we're working on resolving the isse :)
