### ISSUE TITLE
register-snap: selected brandstore resets to Global upon validation

### ISSUE THREAD

**Issue by xnox** [canonical/snapcraft.io#4392]
### Expected behaviour

After selecting a brandstore the value selected persist after clicking register snap; even if redirected to an error or confiramtion page.

### Steps to reproduce the problem

1. Go to https://snapcraft.io/register-snap
1. Select a brand store (i.e. not global)
1. Type name "snapd"
1. Click register snap
2. Observe redirect with an error
3. observe that url has form settings encoded "?snap_name=snapd&is_private=False&store=BRANDSTOREID&conflict=True"
4. observe that whilst the form has settings preserved for the snap name, privacy setting, notice that the store field got reset back to global
5. if the error message displayed is overridable, one may click submit again, and accidently file snap request for the global store instead of the brandstore

Maybe store=BRANDSTOREID value is not correctly mapped back to human-readable store names in the drop down, hence it resets to just global.

### Specs

- _URL:_ https://snapcraft.io/register-snap?snap_name=snapd&is_private=False&store=BRANDSTOREID&conflict=True
- _Operating system:_
- _Browser:_

**Comment by Lukewh** [comment]
This should have been fixed from the above PR. Please reopen if this isn't the case.
