### ISSUE TITLE
By-channel metrics legend (on hover) missing `latest` track if it's not default

### ISSUE THREAD

**Issue by Saviq** [canonical/snapcraft.io#4393]
### Expected behaviour
The on-hover legend of metrics enumerates the major contributors to the total.

### Steps to reproduce the problem
Go to https://snapcraft.io/ubuntu-frame/metrics?active-devices=channel and hover on the graph to see the legend.

![obraz](https://github.com/canonical/snapcraft.io/assets/231077/c6a3c308-056d-49d8-b309-731f78842ded)

### Specs

- _URL:_ https://snapcraft.io/ubuntu-frame/metrics?active-devices=channel
- _Operating system:_ N/A
- _Browser:_ N/A

**Comment by Lukewh** [comment]
I've raised this with the store team as it seems like the store API is indeed not returning the latest channel if it's not default.
