### ISSUE TITLE
Problem with a specific snap 

### ISSUE THREAD

**Issue by gwstern** [canonical/snapcraft.io#4407]
### Expected behaviour

(I couldn't find how to report an issue with an actual snap as opposed to the web site so I apologize for posting this here)

I'm using the runescape launcher that rujak wrote. When I try to install it I get:

> .../snap/runescape-rujak/4/Jagex/launcher/rs2client: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory

All I want to know is where is it looking for the library.

### Specs

- _URL:_
- https://snapcraft.io/install/runescape-rujak/ubuntu
- _Operating system:_
- Ubuntu 22.04
- _Browser:_
- N/A

**Comment by steverydz** [comment]
Hi @gwstern

We're not able to debug any issues with snaps themselves. I've managed to locate the repo for this Snap on GitHub so I'd suggest filing an issue there: https://github.com/SirRujak/runescape-rujak/issues/new
