### ISSUE TITLE
On Ubuntu Core snap list should display only snaps with 'restricted confinement'

### ISSUE THREAD

**Issue by pjgoodall** [canonical/snapcraft.io#4419]
### Expected behaviour

snap find editor --confinement=strict

I am using Ubuntu Core on a Raspberry-pi 2B. I can only install snaps with a strict confinement model.

I would expect either a filter for the confinement model, or only feasibly installable snaps to be returned. There would be no classic confinement model snaps returned. 

### Specs

- _URL:_
- [Ubuntu Core](https://ubuntu.com/core)
```
~$ cat /etc/os-release
NAME="Ubuntu Core"
VERSION="22"
ID=ubuntu-core
PRETTY_NAME="Ubuntu Core 22"
VERSION_ID="22"
```
- _Browser:_
system terminal

**Comment by Lukewh** [comment]
Hi, This issue tracker is for the website snapcraft.io. You can file a feature request against SnapD here: https://bugs.launchpad.net/snapd Thanks :)
