### ISSUE TITLE
"Last Updated" date is misleading

### ISSUE THREAD

**Issue by setharnold** [canonical/snapcraft.io#4424]
### Expected behaviour

The snapstore webpage includes a `Last Updated` date on individual snap pages; this date appears to be something like a stable channel, rather than the actual latest change.

### Specs

- _URL:_ https://snapcraft.io/uefi-fw-tools
- _Operating system:_ Ubuntu Focal
- _Browser:_ Firefox

The text on this page says:

```
Last updated

    4 October 2021
```

But the drop-down of versions shows one that's newer than that:

```
20/beta 	confined-1.7.0+gitc62eec9 	18 January 2022
```

Thanks

**Comment by Lukewh** [comment]
You're correct, it does show when the last update to stable was. I think one solution would be to update the heading to “Last stable update”. Another solution may be to keep the heading but have 2 items below:
```
Last updated
  4 October 2021 (latest/stable) <-- The latest stable release
  18 January 2022 (20/beta)       <-- The latest release from any other channel
```

@AnnSoMuller what do you think?

**Comment by AnnSoMuller** [comment]
The last update date should be the latest, 

18 January 2022
--
And indeed it's valuable to have the latest stable update too, so I'm in favour or the second option @Lukewh with the latest update on top => 18 January 2022 (20/beta)
