### ISSUE TITLE
Cannot log in to snapcraft.io

### ISSUE THREAD

**Issue by ctigrisht** [canonical/snapcraft.io#4461]
### Expected behaviour
Should be able to access the snapcraft.io account

### Steps to reproduce the problem
Login to snapcraft.io website, will ask for credentials, then will put out a 404 after login, if already logged in via oauth will just throw 404, it can also fail to a blank page saying ~No data received or something like that (could not reproduce). Peer confirmed by other discord member

### Specs

- _URL:_ https://snapcraft.io/login
- _Operating system:_ Fedora Linux 39
- _Browser:_ Brave

**Comment by Lukewh** [comment]
Hi @ctigrisht can you try removing all cookies associated with snapcraft.io and try again? We had a small change to auth recently that may cause some legacy cookies to cause a weird state - thanks!

**Comment by ctigrisht** [comment]
> Hi @ctigrisht can you try removing all cookies associated with snapcraft.io and try again? We had a small change to auth recently that may cause some legacy cookies to cause a weird state - thanks!

I tried and it doesn't work, probably the ubuntu account cookie/token is not accepted by snapcraft website

**Comment by mlanighan** [comment]
Seeing this issue with a new ubuntu account. Tried clearing cookies as suggested and it did not fix the problem.

**Comment by Lukewh** [comment]
@ctigrisht @mlanighan if you go to https://dashboard.snapcraft.io, can you sign in?

We'll be taking a deep dive into this issue early next week, I apologize for the disruption.

**Comment by ctigrisht** [comment]
@Lukewh The dashboard works fine, but not snapcraft

**Comment by mlanighan** [comment]
@Lukewh  Seeing the same-I can log into the dashboard but not snapcraft.io

**Comment by gdoumen** [comment]
@Lukewh  I'm seeing the same

**Comment by herzkoenig** [comment]
I am experiencing the same difficulties. Login via the dashboard is working.

Additionally, I am unable to login via `snap login` in my WSL terminal.

```
root@myUserName:~# snap login mymail@adress.com
Personal information is handled as per our privacy notice at
https://www.ubuntu.com/legal/dataprivacy/snap-store

Password of "mymail@adress.com":
error: access denied (see 'snap help login')
```

Is that maybe related to this ticket?

**Comment by ctigrisht** [comment]
@Lukewh It seems I can now log into snapcraft.io
![image](https://github.com/canonical/snapcraft.io/assets/43137837/fd850c9d-c1a4-4fd9-a06b-b1ff16193579)

**Comment by julienrbrt** [comment]
I was able to replicate this (OS: Fedora 39, Browser: Chromium).
I had to login to the dashboard first to be able to be logged in it `snapcraft.io`.
