### ISSUE TITLE
Uploading screenshots gives 500 error

### ISSUE THREAD

**Issue by merlijn-sebrechts** [canonical/snapcraft.io#4468]
### Expected behaviour

Uploading screenshots works

### Steps to reproduce the problem

Upload any screenshot to any snap listing.

### Specs

Tested both with Firefox and Chrome.

## Error output as screenshot because I'm a duck

![image](https://github.com/canonical/snapcraft.io/assets/1492981/d23e5009-e8bb-45b1-a41c-009ff1c08783)

**Comment by Lukewh** [comment]
hi @merlijn-sebrechts I'm not having any issues uploading test images. Could you provide an example image that doesn't work, please?

**Comment by Lukewh** [comment]
@merlijn-sebrechts if you notice any more issues, please reopen this and tag me!
