### ISSUE TITLE
Urban-terrir snap doesn't works any more after update though non snap urban-terror still works

### ISSUE THREAD

**Issue by lanigb** [canonical/snapcraft.io#4490]
%urban-terror 
ioQ3 1.35 urt 4.3.4 linux-x86_64 Oct 12 2023
----- FS_Startup -----
Current search path:
/home/alain/snap/urban-terror/73/.q3a/q3ut4
/home/alain/snap/urban-terror/73/.q3a/q3ut4/download/x_ut4_rctf1.pk3 (11 files)

[...]
----------------------
24361 files in pk3 files
execing default.cfg
"MINUS" isn't a valid key
"PLUS" isn't a valid key
execing q3config.cfg
couldn't exec autoexec.cfg
Hunk_Clear: reset the hunk ok
----- Client Initialization -----
----- Initializing Renderer ----
-------------------------------
QKEY found.
----- Client Initialization Complete -----
----- R_Init -----
...loading libGL.so.1:
Calling SDL_Init(SDL_INIT_VIDEO)...
SDL_Init(SDL_INIT_VIDEO) passed.
Initializing OpenGL display
...setting mode 16: 1920 1080
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error:  BadValue
  Request Major code 152 (GLX)
  Request Minor code 3 ()
  Value 0x0
  Error Serial #47
  Current Serial #48

### Expected behaviour
command urban-terror should launch the  game
### Steps to reproduce the problem
Game was OK until 2023-12-23 update
Urban-terror from urban-terror home works.
glxgears works
### Specs

- _URL:_
- _Operating system:_Linux 6.6.8-1-siduction-amd64 #1 SMP PREEMPT_DYNAMIC siduction 6.6-8 (2023-12-20) x86_64 GNU/Linux      
- _Browser:_

**Comment by Lukewh** [comment]
Hi @lanigb it looks like you have an issue with the Urban Terror Snap. This issue tracker is for the snapcraft.io website, you can file an issue on the Urban Terror Snap github repo here: https://github.com/predr/urban-terror-snap/issues. Thanks.
