### ISSUE TITLE
Malware: https://snapcraft.io/sparrow-wallet

### ISSUE THREAD

**Issue by craigraw** [canonical/snapcraft.io#4517]
Hi,

I am the developer of Sparrow Wallet, a well known open source Bitcoin wallet. The website for it is at https://sparrowwallet.com/, and the source at https://github.com/sparrowwallet/sparrow.

I have just been alerted to malware which has been published at https://snapcraft.io/sparrow-wallet. From the screenshots it is clear that it is attempting to masquerade as Sparrow Wallet. However, on closer inspection it is clearly not Sparrow - the size of the download, version number and architecture of the software are all dramatically different. 

It is my belief that you are hosting a malware application which will seek to steal funds. Please can you take appropriate action.

Thanks,
Craig

PS This malware has already been reported and taken down on flathub.

**Comment by wgrant** [comment]
Thanks for the report. We've taken down the snap, and are investigating further.

**Comment by Lukewh** [comment]
Thanks @craigraw this has been dealt with so I'm going to close the issue. If you have any other concerns please let us know.
