### ISSUE TITLE
(NaN%) in graphs

### ISSUE THREAD

**Issue by popey** [canonical/snapcraft.io#4562]
### Expected behaviour

0%

### Steps to reproduce the problem

Visit one of the many lovely charts on the snapcraft website. Hover over a graph to see a breakdown popup. Note that where no data is available, '(NaN%)' appears.

![image](https://github.com/canonical/snapcraft.io/assets/1841272/25c4179b-6e06-4c93-b657-094275879eed)

### Specs

- _URL:_ https://snapcraft.io/forgejo/metrics?active-devices=architecture
- _Operating system:_ macOS
- _Browser:_ Microsoft Edge

**Comment by chillkang** [comment]
https://github.com/canonical/snapcraft.io/pull/4579
