### ISSUE TITLE
Unable to sign in - redirection loop

### ISSUE THREAD

**Issue by bunniseng** [canonical/snapcraft.io#4577]
### Expected behaviour

When signing into snapcraft.io, I am logged into the landing page of the snapcraft portal.

@steverydz @chillkang - this relates to issue #4572 

by the way this is not fixed, it's actually worse, now when signing in I get a redirection loop with "OpenID transaction in progress" in the title with a blank screen.

### Steps to reproduce the problem

1. as a newly signed up user
2. go to https://snapcraft.io
3. login

### Specs

- https://snapcraft.io/login?next=/account/agreement&openid_complete=yes&xxxxxxx
- OSX
- Firefox

**Comment by steverydz** [comment]
@bunniseng This change has been reverted so I'll close this issue. We'll continue to track it at https://github.com/canonical/snapcraft.io/issues/4572
