### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by SusheelaHegde05** [canonical/snapcraft.io#4585]
Developer identifier can be retrieved with the [snapcraft](https://snapcraft.io/docs/snapcraft-overview?_gl=1*o0a4k4*_gcl_au*MTE5NDU3OTYxLjE3MTI1MzMxNTU.&_ga=2.179232676.1296944509.1712586683-61723397.1712586683) command,

1. Create an Ubuntu One account
2. To retrieve developer account ID, open https://snapcraft.io/docs/snapcraft-overview?_gl=1*1os3bee*_gcl_au*MTE5NDU3OTYxLjE3MTI1MzMxNTU.&_ga=2.19166392.1296944509.1712586683-61723397.1712586683
3.  try to login 
4. see above internal server error

**Comment by steverydz** [comment]
@SusheelaHegde05 Thank you for reporting this issue. We are looking into it.

**Comment by Lukewh** [comment]
This should be resolved now, thanks!
