### ISSUE TITLE
Internal Server Error logging into snapcraft.io

### ISSUE THREAD

**Issue by bruno-garcia** [canonical/snapcraft.io#4589]
### Expected behaviour

Log in

Failed but status page is all green

### Steps to reproduce the problem

I created a new account. And before verifying the email, I added another email. Then I opened the first email confirmation link and already saw Internal Server Error after trying to agree to the terms of _Developer Programme Agreement
_. Same when I clicked on the second verification link (of my second email address).

Now I can reproduce the 500 simply by:

Login to https://login.ubuntu.com/

Confirm I recently been to snapcraft.io:
![image](https://github.com/canonical/snapcraft.io/assets/1633368/630ad5ca-70e0-4054-a813-923bf69ebea3)

Browse https://snapcraft.io/

Try to login at the top

![image](https://github.com/canonical/snapcraft.io/assets/1633368/2abd84c2-7a6e-46a4-9ab2-34869b235cbe)

![image](https://github.com/canonical/snapcraft.io/assets/1633368/4c72e93c-93ec-4612-b34d-8e60754a1429)

### Specs

- _Operating system:_
macOS Sonoma
- _Browser:_
Chrome: Version 123.0.6312.107 (Official Build) (arm64)

### Sentry

I noticed [there's Sentry in this repo](https://github.com/search?q=repo%3Acanonical%2Fsnapcraft.io%20sentry&type=code). But when inspecting on the failed page, I couldn't find it loaded. So I assume no error event/trace data to help debug?

Also "report an error" takes me here. Note that [Sentry has a new User Feedback widget](https://docs.sentry.io/product/user-feedback/) that linked to telemetry helpful for debugging like errors, traces and session replay (all text redacted but still useful for debugging)

**Comment by steverydz** [comment]
@bruno-garcia Thank you for reporting this issue. We are looking into it.
