### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by PaSharks9** [canonical/snapcraft.io#4591]
### Expected behaviour
I create my Ubuntu ONe Account and i try to access and authenticate in Canonical Snapcraft . 
### Steps to reproduce the problem
Once i agree with to the terms and privacy notice i click to continue but i get a page with Internal Server Error
### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by steverydz** [comment]
@PaSharks9 Thank you for reporting this issue. We are looking into it.

**Comment by Lukewh** [comment]
This should be resolved now, thanks!
