### ISSUE TITLE
Snap store instructions are inaccurate

### ISSUE THREAD

**Issue by evilnick** [canonical/snapcraft.io#4611]
The page for editing snap store entries claims: 

```
Code: Text indented with 3 spaces of inside `
```

I believe this should say 'or'

**Comment by samuelallan72** [comment]
Currently this reads:

    Code: Text indented with 3 spaces of ` inside

It probably should read something like:

    Code: Text indented with 3 spaces or inside `

Or maybe:

    Code: Text indented with 3 spaces or inside single backticks (eg. `code`)


An example would be good to clarify here.
