### ISSUE TITLE
Can't switch user

### ISSUE THREAD

**Issue by laszukdawid** [canonical/snapcraft.io#4618]
### Expected behaviour

After logging in as user A, we should be allowed to log out and log in as user B.

### Steps to reproduce the problem

Log in as user A. Log out. Try to log in. It doesn't ask for login details, it straight out logs back in as user A.

Might be due to associating account with google. The only way I can do anything with snapcraft is through Firefox Private session.

### Specs

- _URL:_
- _Operating system:_ `Linux fedora 6.8.8-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Apr 27 17:42:13 UTC 2024 x86_64 GNU/Linux`
- _Browser:_ Firefox 125.0.3 (64-bit)

**Comment by Lukewh** [comment]
Hi, sorry for the delay in response. This is due to the use of https://login.ubuntu.com. The only true way to log out is to visit https://login.ubuntu.com and click logout on that website. Sorry for the inconvenience.
