### ISSUE TITLE
there are two search pages for the store

### ISSUE THREAD

**Issue by wxl** [canonical/snapcraft.io#4623]
### Expected behaviour
Clicking on any link on snapcraft.io that appears to lead to the store will result in a search functionality that works correctly.

### Steps to reproduce the problem
Follow along and you'll see the issue:
 1. Go to snapcraft.io
 1. Enter "foo" and hit enter
 1. Results come up with foobar2000 at the top of the list (as it does if you were to `snap search foo`)
 1. Note the URI ends in **search**?q=foo
 1. Click on the "Snap Store" link at the top of the page (https://snapcraft.io/store)
 1. Note the page looks identical to the previous one
 1. Repeat step 2
 1. There are no results
 1. Note the URI ends in **store**?q=foo
 
### Specs

- _URL:_ https://snapcraft.io/store
- _Operating system:_ Kubuntu
- _Browser:_ Firefox

**Comment by steverydz** [comment]
@wxl Thanks for reporting this. It is now fixed.
