### ISSUE TITLE
Pagination at the snapcraft.io site is not working right

### ISSUE THREAD

**Issue by akarabelnikov** [canonical/snapcraft.io#4649]
### Expected behaviour
Exploring the whole list of an applications using pagination buttons.

### Steps to reproduce the problem

1) Explore the list of application, for example the list of games
![image](https://github.com/canonical/snapcraft.io/assets/16856588/24c0bba7-dffa-4809-a974-edfc79aad32b)
2) Click on the "Next page" button several times
![image](https://github.com/canonical/snapcraft.io/assets/16856588/bdbaa234-2cec-4d38-84ee-e5d4aebf7d18)
3) On the page number 7 (or sometimes at page number 8 or 9) the pagination is breaking on - the use can't explore the whole list till the end.
![image](https://github.com/canonical/snapcraft.io/assets/16856588/710b504b-bd5d-467c-92be-d3bdce0faa07)

The lenght of list for this category (games) is about 20 pages (I checked several monthes ago).

### Specs

- _URL:_ https://snapcraft.io/search?category=games&page=8
- _Operating system:_ Windows 11
- _Browser:_ Opera 109.0.5097.80, Google Chrome 117.0.5938.132

It worked ok several weeks ago.

**Comment by Lukewh** [comment]
We believe this issue is now fixed. If not please reopen this issue. Thanks for the report!
