### ISSUE TITLE
Cannot access the website

### ISSUE THREAD

**Issue by Synaxis** [canonical/snapcraft.io#4708]
### Steps to reproduce the problem
try to access the website https://snapcraft.io/snapcraft

### Issue:
"Please try again later
You can check the service status at [status.snapcraft.io](https://status.snapcraft.io/).

If the problem persists please check the Snapcraft [forum](https://forum.snapcraft.io/) or [report an issue](https://github.com/canonical-web-and-design/snapcraft.io/issues/new)." 
### Specs

- _URL:_ https://snapcraft.io/snapcraft
- _Operating system:_ Debian 12 amd x64 / Q4OS  
- _Browser:_ Google chrome official latest

**Comment by Synaxis** [comment]
![Screenshot_20240620_104246](https://github.com/canonical/snapcraft.io/assets/29115371/686be4b8-1f9e-4e6e-a28b-58adc27c4518)

**Comment by macoskey** [comment]
Same issue when trying to access https://snapcraft.io/firefox. Receiving a 503 on Google Chrome with both MacOS 14.1 and Ubuntu 22.04.4.

![Screenshot 2024-06-20 at 9 43 30 AM](https://github.com/canonical/snapcraft.io/assets/17714388/6920d54a-4016-49d5-b5ba-6bc9a8372004)

**Comment by macoskey** [comment]
Seems to have been resolved 👍
