### ISSUE TITLE
not able to load https://snapcraft.io/admin/account 

### ISSUE THREAD

**Issue by IbtsamRana** [canonical/snapcraft.io#4784]
### Specs

- _URL:_
- _Operating system:_
- _Browser:_

- [ ] This issue is related to the snapcraft.io website itself (and not a specific snap).

<img width="1435" alt="Screenshot 2024-07-31 at 2 16 54 PM" src="https://github.com/user-attachments/assets/1450820a-b310-41de-861a-ff6abbccf3b7">

**Comment by steverydz** [comment]
Thanks for raising this issue. We've not been able to replicate this. Could you please delete your cookies and clear your cache and try again?

**Comment by Lukewh** [comment]
If this issue is still relevant, please reopen this issue.
