### ISSUE TITLE
cannot access to My Store and My account pages

### ISSUE THREAD

**Issue by jayc-can** [canonical/snapcraft.io#4786]
### Expected behaviour
successfully load the page content

### Open a private / incognito page in a browser (Chrome in my case) 
visit the URL https://snapcraft.io/admin/account  and https://snapcraft.io/admin/
at the time [status.snapcraft.io](https://status.snapcraft.io/). is all good

### Specs
- _URL: https://snapcraft.io/admin/
- _Operating system: Ubuntu 22.04, 
5.15.0-117-generic #127-Ubuntu SMP /  x86_64 GNU/Linux
- _Browser: Chrome Version 127.0.6533.72 (Official Build) (64-bit)

- [ ] This issue is related to the snapcraft.io website itself (and not a specific snap).

**Comment by steverydz** [comment]
Thanks for raising this issue. We've not been able to replicate this. Could you please delete your cookies and clear your cache and try again?

**Comment by jayc-can** [comment]
tried again and it seems working now.
