### ISSUE TITLE
A search with nothing found does not provide reasonable feedback

### ISSUE THREAD

**Issue by mhampl** [canonical/snapcraft.io#4808]
### Expected behaviour
When searching for something that does not exist, I expect to get a response which tells that "nothing has been found" for my search term, but what I get on snapcraft.io is a screen with the black header, the black footer and just an empty white stripe without any information between those.

### Steps to reproduce the problem
Open snapcraft.io and search for "nonexisting" or anything else that does not give a match,
or directly open https://snapcraft.io/store?q=nonexisting

### Specs
- _URL:_ https://snapcraft.io and https://snapcraft.io/store?q=nonexisting
- _Operating system:_ Microsoft Windows 11 with Chrome and Ubuntu 22.04 with Firefox
- _Browser:_ Chrome on Microsoft Windows 11 and Firefox on Ubuntu 22.04

- [x] This issue is related to the snapcraft.io website itself (and not a specific snap).

**Comment by brlin-tw** [comment]
It seems that this issue is no longer reproduced:

![Screenshot](https://github.com/user-attachments/assets/93dc1e82-d83c-4e07-9836-3858598da44c)

**Comment by mhampl** [comment]
I can confirm that the issue does not appear any more. I am not sure whether it has been solved or has disappeared for an unknown reason. In any case, it can be closed.
