### ISSUE TITLE
Snap account not working properly.

### ISSUE THREAD

**Issue by ilianTsonev** [canonical/snapcraft.io#4818]
### Expected behaviour
Show info for my account
### Steps to reproduce the problem
Logged in my account and clicked "account details"   //yet i can register snap names
### Specs

- _URL:_ https://snapcraft.io/admin/account
- _Operating system:_ Ubuntu 24.02 Noble Numbat
- _Browser:_ Firefox

- [Y] This issue is related to the snapcraft.io website itself (and not a specific snap).

**Comment by Lukewh** [comment]
Can you provide more information, please? There isn't a lot of detail to go on here. Thanks

**Comment by ilianTsonev** [comment]
I think I need to close this... it's all fixed now!

**Comment by Lukewh** [comment]
🥳  thanks @ilianTsonev
