### ISSUE TITLE
snap is uncontrollable trash

### ISSUE THREAD

**Issue by HennoRickowski** [canonical/snapcraft.io#4840]
it is basically impossible to not use a snap package, if it exists.
i have the mozilla ppa for firefox.
i've put a higher prio in apt, for the ppa, so the snap meta package gets ignored, which.. wont work.
i've also put the snap to "disabled", "held", without a time limit.

every now and then.. the system just updates firefox to the snap meta package, which is even diabled.

so basically.. im working in firefox, it tells me to restart it, and refuses to work, because it got auto updated, (which i explicitly told to not to do, remember)
when i do restart it.. it wont, because its now the outdated, disabled snap!
then i have to manually perform an apt upgrade, to "downgrade" to the ppa version.

### Expected behaviour

that there is atleast one feature in snap, which is supposed to disable auto updates, which ACTUALLY WORKS!!!

### Steps to reproduce the problem

- use ubuntu

### Specs

- Ubuntu 22.04

- [X] This issue is related to the snap itself (and not a specific snap).

**Comment by JGCarroll** [comment]
This occurs because the priority on the Ubuntu repository is higher than the priority on the Mozilla repository/PPA, if you assign the priority to be higher, this problem will stop occuring.

What's actually happening here is that Apt keeps reinstalling the snap Firefox package, not snap itself, which is why the hold command does nothing.

**Comment by HennoRickowski** [comment]
> This occurs because the priority on the Ubuntu repository is higher than the priority on the Mozilla repository/PPA, if you assign the priority to be higher, this problem will stop occuring.
> 
> What's actually happening here is that Apt keeps reinstalling the snap Firefox package, not snap itself, which is why the hold command does nothing.

incorrect.
as mentioned, a did pinning on apt level.
here is my /etc/apt/preferences.d/firefox-snapless:
```
Package: firefox
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1000
```

apt handles this perfectly fine, the problem is the snapd service, which ignores everything and just does its thing, whenever it wants, even while using those apps.

**Comment by Lukewh** [comment]
For help with snapd you can post on https://forum.snapcraft.io or open an issue on https://github.com/canonical/snapd. The snapd Engineers generally don't watch this issue tracker as it's specifically for the snapcraft.io website. Thanks.
