### ISSUE TITLE
spdx link is broken

### ISSUE THREAD

**Issue by popey** [canonical/snapcraft.io#4856]
### Expected behaviour

I want to fill in a custom SPDX license for an uploaded snap.

### Steps to reproduce the problem

1. Go to the listing page for a snap
2. Scroll down to the license field.
3. Click "Custom SPDX expression" radio button
4. Click the revealed "Visit [SPDX Specification 21](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60) for more information." link
5. Note the link is broken

![image](https://github.com/user-attachments/assets/d4d25c00-fcfd-4708-be40-7ea0db2a4ac2)

I have filed an [issue upstream](https://github.com/spdx/spdx-spec/issues/1122) (which I think is the right place, but who knows?), but you may want to change the link in the store in the meantime because 2.1 is an outdated SPDX spec anyway.

### Specs

- _URL:_ https://snapcraft.io/defold/listing
- _Operating system:_ macOS (sorry)
- _Browser:_ Chrome (sorry²)

- [X] This issue is related to the snapcraft.io website itself (and not a specific snap).

**Comment by steverydz** [comment]
Thanks @popey. This is now fixed.
