### ISSUE TITLE
Badges have `Cross-Origin-Resource-Policy: same-site`

### ISSUE THREAD

**Issue by Saviq** [canonical/snapcraft.io#4866]
### Expected behaviour
https://mir-server.io/docs/releases shows the release badges.

### Steps to reproduce the problem
Go to https://mir-server.io/docs/releases, see no badges.

### Specs

- _URL:_ https://mir-server.io/docs/releases
- _Operating system:_ N/A
- _Browser:_ N/A

- [x] This issue is related to the snapcraft.io website itself (and not a specific snap).

**Comment by Lukewh** [comment]
We believe this to have been fixed by https://github.com/canonical/snapcraft.io/pull/4869. Please reopen if this isn't the case.
