### ISSUE TITLE
`Add Track` & `Request Track` buttons in Snap Release page unavailable on Safari

### ISSUE THREAD

**Issue by JGCarroll** [canonical/snapcraft.io#4878]
Adding this report based on a conversation in the forums here:
https://forum.snapcraft.io/t/request-for-tracks-cmake/11789/36

My guess is that the naming conventions of the button/surrounding classes is triggering some heuristics in the browser that cause it to be treated like a tracking pixel/etc, and thus removed entirely.

### Expected behaviour
Either the "Add Track" or "Request Track" button should be visible, like so:
![cd22c39d4e36f64ee9f79be21f98f01ed9bcdeb7](https://github.com/user-attachments/assets/7e486bf3-3505-4612-b052-fa256858872f)

However on  Safari, it appears to just simply not appear at all, like the following from the linked thread:
<img width="123" alt="e55ec8bde13b027fc5fd5d5eb967209096f17e79_2_245x500" src="https://github.com/user-attachments/assets/867992f2-de81-4752-a1d7-397e95f5147c">

### Steps to reproduce the problem
Open release page in Safari

### Specs

- _URL:_ snapcraft.io/$SNAP/releases
- _Browser:_ Safari

- [Y] This issue is related to the snapcraft.io website itself (and not a specific snap).

**Comment by jmgiaever** [comment]
Applies to Chrome on Linux/Ubuntu 24.04.1 too.

**Comment by abbiesims** [comment]
Hi @JGCarroll, thanks for reporting. There was a recent change merged related to the track dropdown. Can you please clear your cache and try logging in with a fresh session and let me know if the problem persists?

**Comment by abbiesims** [comment]
We pushed a fix for this so will close the issue. Please reopen it if the problem persists.

**Comment by jmgiaever** [comment]
Hi,

This issue seems to be back again. Been like it for the past week at least. Not allowed to re-open the issue.

**Comment by abbiesims** [comment]
Hi @jmgiaever,

I have just tested this on Chrome (Linux, Ubuntu 24.04) and on Safari on MacOS (Sonoma 14) and it seems to be working fine for me on both. Can you tell me where it has not been working for you? Thanks.

**Comment by jmgiaever** [comment]
Hi @abbiesims,

It seems to be working again now, but for days (last week), I had to delete all cookies for snapcraft.io and login again, for it to show up again.

Not sure why! However I haven't been active on snapcraft.io for a few days, until now, and it shows as expected. I assume there's just been some hickups somewhere. (I have Privacy Badger etc disabled for this website).

**Comment by abbiesims** [comment]
Hi @jmgiaever, no problem. We have had some issues with this feature in the past but it has seemed to be stable for a while now. Please do let me know if you face the problem again! Thanks.
