### ISSUE TITLE
Popup is not readable for latest values on metrics page

### ISSUE THREAD

**Issue by tbille** [canonical/snapcraft.io#4909]
### Expected behaviour

The popup on the metrics page should not go outside of the browser view

<img width="396" alt="Screenshot 2024-11-19 at 21 12 22" src="https://github.com/user-attachments/assets/5bb46885-078c-4965-832b-9b413553e2ab">

### Steps to reproduce the problem

- Go to the metrics page of any snap
- Highlight the latest date
- Notice that we can't read the values of the latest dates

### Specs

- _URL:_ `https://snapcraft.io/<SNAP>/metrics`
- _Browser:_ chrome

- [x] This issue is related to the snapcraft.io website itself (and not a specific snap).

**Comment by Lukewh** [comment]
Related issue: https://github.com/canonical/snapcraft.io/issues/4861
