### ISSUE TITLE
Trying to change my name on Snap Store

### ISSUE THREAD

**Issue by sblantipodi** [canonical/snapcraft.io#4919]
### Expected behaviour

I would like to change my name on snap store and on my app.

![image](https://github.com/user-attachments/assets/0323f02f-6a15-4da7-b36e-2c3a22740d84)

Please fix it.

My app report only "Davide" as the name of the author,
I would like to specify my surname too please.

![image](https://github.com/user-attachments/assets/0cbd75d5-ec51-4391-8777-873531359af4)

**Comment by cosmic-zip** [comment]
It seeings normal for me after update, anyway try refresh the store:
```

sudo killall snap-store
sudo snap refresh snap-store
```

![Screenshot from 2024-11-29 22-39-16](https://github.com/user-attachments/assets/89a08b9c-4be5-4040-b64e-f71052e706a5)
